# ------------------ pure ------------------- 
format = """
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$kotlin\
$golang\
$c\
$cpp\
$line_break\
$character"""

[fill]
symbol = " "

# Hostname in soft retro blue
[hostname]
ssh_only = true
format = "[@$hostname]($style) "
style = "bold fg:#74b9ff"  # Retro blue
disabled = false 

# Directory with warm orange/yellow gradient feel
[directory]
style = "bold fg:#f5d5ae"  # Warm yellow/orange - same as palette = 6 on Ghostty theme 
read_only = " üîí"
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "Ôêò"
format = "[$symbol $branch]($style)"
style = "#6C6C6C"

[git_status]
format = "[[($conflicted$untracked$modified$renamed$deleted)](218)[($staged)](green)($diverged$ahead_behind$stashed)](#00cec9)"
up_to_date = ""
ahead = "‚á°"
behind = "‚á£"
diverged = "‚áï"
untracked = "*"
modified = "!"
staged = "+"
renamed = "¬ª"
deleted = "‚úò"
stashed = "‚â°"
conflicted = "‚ö°"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[character]
success_symbol = "[\\$](bold fg:#00cec9)"  # Mint green dollar sign
error_symbol = "[!!](bold fg:#ff7675)"    # Soft red dollar sign
vicmd_symbol = "[\\$](bold blue)"    # Yellow dollar sign for vi mode


[c]
symbol = "Óòû "
style = "bg:color_blue"
format = '[[ $symbol( $version) ]()]($style)'

[cpp]
symbol = "Óòù "
style = "bg:color_blue"
format = '[[ $symbol( $version) ]()]($style)'

[rust]
symbol = "ü¶Ä"
style = "bg:color_blue"
format = '[[ $symbol( $version) ]()]($style)'

[golang]
symbol = "üêπ"
style = "bg:color_blue"
format = '[[ $symbol( $version) ]()]($style)'

[java]
symbol = "‚òï"
style = "bg:color_blue"
format = '[[ $symbol( $version) ]()]($style)'

[kotlin]
symbol = "Óò¥"
style = "bg:color_blue"
format = '[[ $symbol( $version) ]()]($style)'


# ------------------ gruvbox style  -----------------------
# "$schema" = 'https://starship.rs/config-schema.json'
#
# format = """
# [ÓÇ∂](color_orange)\
# $username\
# [ÓÇ∞](bg:color_yellow fg:color_orange)\
# $directory\
# [ÓÇ∞](fg:color_yellow bg:color_aqua)\
# $git_branch\
# [ÓÇ∞](fg:color_aqua bg:color_blue)\
# $c\
# $cpp\
# $rust\
# $golang\
# $java\
# $kotlin\
# $python\
# [ÓÇ∞](fg:color_blue bg:color_bg3)\
# $docker_context\
# [ÓÇ∞](fg:color_bg3 bg:color_bg1)\
# $time\
# [ÓÇ¥ ](fg:color_bg1)\
# $line_break$character"""
#
# palette = 'gruvbox_dark'
#
# [palettes.gruvbox_dark]
# color_fg0 = '#fbf1c7'
# color_bg1 = '#3c3836'
# color_bg3 = '#665c54'
# color_blue = '#458588'
# color_aqua = '#689d6a'
# color_green = '#98971a'
# color_orange = '#d65d0e'
# color_purple = '#b16286'
# color_red = '#cc241d'
# color_yellow = '#d79921'
#
# [os]
# disabled = true # false to enable os icon
# style = "bg:color_orange fg:color_fg0"
#
# [os.symbols]
# Macos = "Û∞Äµ"
#
# [username]
# show_always = true
# style_user = "bg:color_orange fg:color_fg0"
# style_root = "bg:color_orange fg:color_fg0"
# format = '[ $user ]($style)'
#
# [directory]
# style = "fg:color_fg0 bg:color_yellow"
# format = "[ $path ]($style)"
# truncation_length = 1
# truncation_symbol = "‚Ä¶/"
#
# [git_branch]
# symbol = "Ôêò"
# style = "bg:color_aqua"
# format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'
#
# [git_status]
# style = "bg:color_aqua"
# format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'
#
# [c]
# symbol = "Óòû "
# style = "bg:color_blue"
# format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
#
# [cpp]
# symbol = "Óòù "
# style = "bg:color_blue"
# format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
#
# [rust]
# symbol = "ü¶Ä"
# style = "bg:color_blue"
# format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
#
# [golang]
# symbol = "üêπ"
# style = "bg:color_blue"
# format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
#
# [java]
# symbol = "‚òï"
# style = "bg:color_blue"
# format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
#
# [kotlin]
# symbol = "Óò¥"
# style = "bg:color_blue"
# format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
#
# [python]
# symbol = "üêç"
# style = "bg:color_blue"
# format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
#
# [docker_context]
# symbol = "üê≥"
# style = "bg:color_bg3"
# format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'
#
# [time]
# disabled = false
# time_format = "%R"
# style = "bg:color_bg1"
# format = '[[ Ôê∫ $time ](fg:color_fg0 bg:color_bg1)]($style)'
#
# [line_break]
# disabled = false
#
# [character]
# disabled = false
# success_symbol = '[Ôê≤](bold fg:color_aqua)'
# error_symbol = '[!!](bold fg:color_orange)'
# vimcmd_symbol = '[Ôê¥](bold fg:color_green)'
# vimcmd_replace_one_symbol = '[Ôê¥](bold fg:color_purple)'
# vimcmd_replace_symbol = '[Ôê¥](bold fg:color_purple)'
# vimcmd_visual_symbol = '[Ôê¥](bold fg:color_blue)'
