format = """
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$kotlin\
$java\
$golang\
$c\
$cpp\
$line_break\
$character"""

add_newline = false

[fill]
symbol = " "

# Hostname in soft retro blue
[hostname]
ssh_only = true
format = "[@$hostname]($style) "
style = "bold fg:#74b9ff"  # Retro blue
disabled = false 

# Directory with warm orange/yellow gradient feel
[directory]
style = "bold fg:#f5d5ae"  # Warm yellow/orange - same as palette = 6 on Ghostty theme 
read_only = " ğŸ”’"
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "ï˜"
format = "[$symbol $branch]($style)"
style = "#6C6C6C"

[git_status]
format = "[[($conflicted$untracked$modified$renamed$deleted)](218)[($staged)](green)($diverged$ahead_behind$stashed)](#00cec9)"
up_to_date = ""
ahead = "â‡¡"
behind = "â‡£"
diverged = "â‡•"
untracked = "*"
modified = "!"
staged = "+"
renamed = "Â»"
deleted = "âœ˜"
stashed = "â‰¡"
conflicted = "âš¡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[character]
success_symbol = "[\\$](bold fg:#00cec9)"  # Mint green dollar sign
error_symbol = "[!!](bold fg:#ff7675)"    # Soft red dollar sign
vicmd_symbol = "[\\$](bold blue)"    # Yellow dollar sign for vi mode

[c]
symbol = "î˜ "
style = "bg:color_blue"
format = '[[ $symbol( $version) ]()]($style)'

[cpp]
symbol = "î˜ "
style = "bg:color_blue"
format = '[[ $symbol( $version) ]()]($style)'

[rust]
symbol = "ğŸ¦€"
style = "bg:color_blue"
format = '[[ $symbol( $version) ]()]($style)'

[golang]
symbol = "ğŸ¹"
style = "bg:color_blue"
format = '[[ $symbol( $version) ]()]($style)'

[java]
symbol = "â˜•"
style = "bg:color_blue"
format = '[[ $symbol( $version) ]()]($style)'

[kotlin]
symbol = "î˜´"
style = "bg:color_blue"
format = '[[ $symbol( $version) ]()]($style)'

